name: media_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  http: ^0.13.3
  json_annotation: ^4.7.0
  visibility_detector: ^0.3.3
  flutter_svg: ^2.0.5
  passwordfield: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3  
  json_serializable: ^6.6.2  

dependency_overrides:
  analyzer: ^5.12.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

