name: media_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.6
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.14
  path: ^1.8.2
  intl: ^0.19.0
  file_picker: ^5.5.0
  provider: ^6.0.3
  http: ^0.13.3
  json_annotation: ^4.7.0
  visibility_detector: ^0.3.3
  flutter_svg: ^2.0.5
  passwordfield: ^0.2.0
  image_picker: ^0.8.4+4
  video_player: ^2.4.7
  permission_handler: ^10.2.0
  youtube_player_flutter: ^9.0.1
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  photo_view: ^0.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3  
  json_serializable: ^6.6.2  

dependency_overrides:
  analyzer: ^5.12.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

